- Cytoscape:
- TPS:
    network:
    timeseries:
    firstscores:
    prevscores:
    source:
    threshold:
- Annotations:
    peptideMapFile:
    timeSeriesFile:
    peptideFirstScores:
    peptidePrevScoreFile:
    windowsFile:
    networkFile:
    goldStandardFile:
    pvalTresh:
    logTransform:
    styleTemplateFile:
    outAnnotFile:
    logDefault:
    addZero:
    repairMissing:
