Cytoscape: 
    path: C:\Users\ajshe\OneDrive\Documents\Comp_bio\Cytoscape_v3.7.1 
    session: "tps_session_test.cys"
TPS:
    required:
        network: data/networks/input-network.tsv
        timeseries: data/timeseries/median-time-series.tsv
        firstscores: data/timeseries/p-values-first.tsv
        prevscores: data/timeseries/p-values-prev.tsv
        source: EGF_HUMAN
        threshold: 0.01
        outlabel: "config-test"
    optional:
        partialmodel: data/resources/kinase-substrate-interactions.sif
        peptidemap: data/timeseries/peptide-mapping.tsv
        outfolder: "None"
        solver: "None"
        slack: "None"
        bitvect: "None"
        no-connectivity: "None"     # bool
        no-temporality: "None"      # bool
        no-monotonicity: "None"     # bool
Annotations: 
    peptideMapFile: data/timeseries/peptide-mapping.tsv
    timeSeriesFile: data/timeseries/log2-fold-change.txt
    peptideFirstScores: data/timeseries/p-values-first.tsv
    peptidePrevScoreFile: data/timeseries/p-values-prev.tsv
    windowsFile: "output_placeholder"
    networkFile: "output_placeholder"
    goldStandardFile: data/resources/eight-egfr-reference-all.txt
    pvalThresh: 0.01
    logTransform: False
    styleTemplateFile: data/templates/tps_style_template.xml
    outAnnotFile: "congig-test"
    outStyleFile: "style_output.xml"
    addZero: True           # default
    logDefault: -1.0        # default
    repairMissing: False    # default